//! Quantum Integrated Information Theory (IIT)
//!
//! Implements Integrated Information Theory (Tononi's Phi) for quantum systems.
//! IIT proposes that consciousness corresponds to integrated information --
//! information generated by a system above and beyond its parts.
//!
//! **World first**: No quantum simulator has built-in IIT consciousness metrics.
//!
//! Phi quantifies the minimum information lost when the system is partitioned
//! into its most independent parts (the Minimum Information Partition, or MIP).
//! A system with high Phi is more than the sum of its parts -- the hallmark
//! of integrated information and, according to IIT, of consciousness.
//!
//! This module provides three formulations:
//!
//! - **Phi 2.0**: Original IIT using Earth Mover's Distance on transition
//!   probability matrices (Tononi 2004).
//! - **Phi 3.0**: Minimum Information Partition formulation using cause-effect
//!   repertoires (Oizumi, Albantakis, Tononi 2014).
//! - **Phi Star (Phi*)**: Practical approximation via quantum mutual information,
//!   much faster than exact Phi 3.0.
//!
//! Additionally, a purely quantum-native geometric Phi is provided, computed
//! directly from the von Neumann entropy of reduced density matrices.
//!
//! # Example
//!
//! ```rust
//! use nqpu_metal::quantum_iit::{QuantumIIT, IITConfig, PhiVersion};
//! use nqpu_metal::{QuantumState, GateOperations};
//!
//! let config = IITConfig::default();
//! let iit = QuantumIIT::new(config);
//!
//! // Create a Bell state (maximally entangled)
//! let mut state = QuantumState::new(2);
//! GateOperations::h(&mut state, 0);
//! GateOperations::cnot(&mut state, 0, 1);
//!
//! let result = iit.compute_phi(&state);
//! assert!(result.phi > 0.0, "Entangled states have positive Phi");
//! ```

use crate::{C64, QuantumState};
use std::fmt;

// ============================================================
// CONSTANTS
// ============================================================

/// Default convergence precision for eigenvalue computation.
const DEFAULT_PRECISION: f64 = 1e-8;

/// Maximum number of Jacobi sweeps for Hermitian eigensolvers.
const MAX_JACOBI_SWEEPS: usize = 200;

/// Threshold below which eigenvalues are treated as zero in entropy calculations.
const ENTROPY_EPSILON: f64 = 1e-15;

// ============================================================
// ERROR TYPES
// ============================================================

/// Errors that can occur during IIT computation.
#[derive(Clone, Debug, PartialEq)]
pub enum IITError {
    /// The requested partition is invalid for the given system size.
    InvalidPartition(String),
    /// Matrix dimensions do not match the expected system size.
    DimensionMismatch {
        expected: usize,
        got: usize,
    },
    /// The transition probability matrix is singular or degenerate.
    SingularTPM(String),
    /// Phi computation failed due to numerical or logical issues.
    PhiComputationFailed(String),
}

impl fmt::Display for IITError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            IITError::InvalidPartition(msg) => write!(f, "Invalid partition: {}", msg),
            IITError::DimensionMismatch { expected, got } => {
                write!(f, "Dimension mismatch: expected {}, got {}", expected, got)
            }
            IITError::SingularTPM(msg) => write!(f, "Singular TPM: {}", msg),
            IITError::PhiComputationFailed(msg) => {
                write!(f, "Phi computation failed: {}", msg)
            }
        }
    }
}

impl std::error::Error for IITError {}

// ============================================================
// ENUMS
// ============================================================

/// IIT formulation version.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PhiVersion {
    /// IIT 2.0: original formulation using Earth Mover's Distance on TPMs.
    Phi2_0,
    /// IIT 3.0: Minimum Information Partition with cause-effect repertoires.
    Phi3_0,
    /// Practical approximation using quantum mutual information. Much faster.
    PhiStar,
}

/// Strategy for searching over partitions to find the MIP.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PartitionStrategy {
    /// Try all bipartitions and find the MIP. Complexity O(2^(n-1)).
    BipartitionSearch,
    /// Try all possible partitions (very expensive, combinatorial explosion).
    Exhaustive,
    /// Partition into individual elements (each qubit is its own part).
    AtomicPartition,
    /// Greedy search for approximate MIP (fast but not guaranteed optimal).
    Greedy,
}

// ============================================================
// CONFIGURATION
// ============================================================

/// Configuration for IIT analysis.
///
/// Use `IITConfig::default()` for sensible defaults, or construct manually
/// for fine-grained control over the computation.
#[derive(Clone, Debug)]
pub struct IITConfig {
    /// Number of qubits in the system.
    pub num_qubits: usize,
    /// Which IIT formulation to use.
    pub phi_version: PhiVersion,
    /// Strategy for searching partitions.
    pub partition_strategy: PartitionStrategy,
    /// Numerical precision for convergence tests.
    pub precision: f64,
}

impl Default for IITConfig {
    fn default() -> Self {
        IITConfig {
            num_qubits: 4,
            phi_version: PhiVersion::Phi3_0,
            partition_strategy: PartitionStrategy::BipartitionSearch,
            precision: DEFAULT_PRECISION,
        }
    }
}

impl IITConfig {
    /// Create a new configuration with explicit qubit count.
    pub fn new(num_qubits: usize) -> Self {
        IITConfig {
            num_qubits,
            ..Default::default()
        }
    }

    /// Set the Phi version.
    pub fn with_phi_version(mut self, version: PhiVersion) -> Self {
        self.phi_version = version;
        self
    }

    /// Set the partition search strategy.
    pub fn with_partition_strategy(mut self, strategy: PartitionStrategy) -> Self {
        self.partition_strategy = strategy;
        self
    }

    /// Set the numerical precision.
    pub fn with_precision(mut self, precision: f64) -> Self {
        self.precision = precision;
        self
    }
}

// ============================================================
// PARTITION
// ============================================================

/// A partition of qubit indices into disjoint subsets.
#[derive(Clone, Debug, PartialEq)]
pub struct Partition {
    /// Each element is a set of qubit indices forming one part.
    pub parts: Vec<Vec<usize>>,
}

impl Partition {
    /// Create a bipartition from a bitmask. Bit i set means qubit i is in part A.
    pub fn from_bitmask(n: usize, mask: usize) -> Self {
        let mut part_a = Vec::new();
        let mut part_b = Vec::new();
        for i in 0..n {
            if (mask >> i) & 1 == 1 {
                part_a.push(i);
            } else {
                part_b.push(i);
            }
        }
        Partition {
            parts: vec![part_a, part_b],
        }
    }

    /// Create an atomic partition (each qubit is its own part).
    pub fn atomic(n: usize) -> Self {
        let parts: Vec<Vec<usize>> = (0..n).map(|i| vec![i]).collect();
        Partition { parts }
    }

    /// Check that the partition covers all qubits exactly once.
    pub fn is_valid(&self, n: usize) -> bool {
        let mut seen = vec![false; n];
        for part in &self.parts {
            for &q in part {
                if q >= n || seen[q] {
                    return false;
                }
                seen[q] = true;
            }
        }
        seen.iter().all(|&s| s)
    }

    /// Total number of qubits across all parts.
    pub fn total_qubits(&self) -> usize {
        self.parts.iter().map(|p| p.len()).sum()
    }
}

impl fmt::Display for Partition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let strs: Vec<String> = self
            .parts
            .iter()
            .map(|p| format!("{{{}}}", p.iter().map(|q| q.to_string()).collect::<Vec<_>>().join(",")))
            .collect();
        write!(f, "{}", strs.join(" | "))
    }
}

// ============================================================
// TRANSITION PROBABILITY MATRIX
// ============================================================

/// Transition Probability Matrix (TPM) for a quantum system.
///
/// TPM[i][j] = P(state j at t+1 | state i at t).
/// Each row is a probability distribution and must sum to 1.
#[derive(Clone, Debug)]
pub struct TransitionProbabilityMatrix {
    /// The matrix stored as `matrix[i][j]`.
    pub matrix: Vec<Vec<f64>>,
}

impl TransitionProbabilityMatrix {
    /// Construct a TPM from a unitary matrix with optional depolarizing noise.
    ///
    /// From unitary U, TPM[i][j] = |U[j][i]|^2 (transition probability from
    /// computational basis state i to state j). With noise parameter p,
    /// the TPM is mixed with the uniform distribution:
    /// TPM = (1-p) * TPM_unitary + p/D * ones
    pub fn from_unitary(unitary: &[Vec<C64>], noise: f64) -> Self {
        let d = unitary.len();
        let mut matrix = vec![vec![0.0; d]; d];

        for i in 0..d {
            for j in 0..d {
                // TPM[i][j] = |U[j][i]|^2 = |<j|U|i>|^2
                matrix[i][j] = unitary[j][i].norm_sqr();
            }
        }

        // Apply depolarizing noise
        if noise > 0.0 {
            let uniform = 1.0 / d as f64;
            for row in matrix.iter_mut() {
                for elem in row.iter_mut() {
                    *elem = (1.0 - noise) * *elem + noise * uniform;
                }
            }
        }

        TransitionProbabilityMatrix { matrix }
    }

    /// Construct a TPM from a quantum channel given as Kraus operators.
    ///
    /// Each Kraus operator is a dim x dim matrix stored as Vec<Vec<C64>>.
    /// TPM[i][j] = sum_k |<j| K_k |i>|^2
    pub fn from_quantum_channel(channel: &[Vec<Vec<C64>>]) -> Self {
        if channel.is_empty() {
            return TransitionProbabilityMatrix {
                matrix: Vec::new(),
            };
        }
        let d = channel[0].len();
        let mut matrix = vec![vec![0.0; d]; d];

        for kraus in channel {
            for i in 0..d {
                for j in 0..d {
                    // <j| K |i> = K[j][i]
                    matrix[i][j] += kraus[j][i].norm_sqr();
                }
            }
        }

        TransitionProbabilityMatrix { matrix }
    }

    /// Dimension of the TPM (number of basis states).
    pub fn dim(&self) -> usize {
        self.matrix.len()
    }

    /// Check that every row sums to 1 (within tolerance).
    pub fn is_stochastic(&self, tol: f64) -> bool {
        for row in &self.matrix {
            let sum: f64 = row.iter().sum();
            if (sum - 1.0).abs() > tol {
                return false;
            }
        }
        true
    }

    /// Extract the sub-TPM for a subset of qubits by marginalizing over others.
    ///
    /// Given a set of qubit indices, produce a TPM acting only on those qubits
    /// by summing over all configurations of the remaining qubits.
    pub fn marginal_tpm(&self, qubits: &[usize], total_qubits: usize) -> TransitionProbabilityMatrix {
        let n_sub = qubits.len();
        let d_sub = 1 << n_sub;
        let d_full = 1 << total_qubits;
        let other_qubits: Vec<usize> = (0..total_qubits)
            .filter(|q| !qubits.contains(q))
            .collect();
        let n_other = other_qubits.len();
        let d_other = 1 << n_other;

        let mut sub_matrix = vec![vec![0.0; d_sub]; d_sub];

        // For each sub-state pair (i_sub, j_sub), sum over all other-qubit configs
        for i_sub in 0..d_sub {
            for j_sub in 0..d_sub {
                let mut total = 0.0;
                for i_other in 0..d_other {
                    let i_full = Self::compose_index(i_sub, qubits, i_other, &other_qubits, total_qubits);
                    for j_other in 0..d_other {
                        let j_full = Self::compose_index(j_sub, qubits, j_other, &other_qubits, total_qubits);
                        if i_full < d_full && j_full < d_full {
                            total += self.matrix[i_full][j_full];
                        }
                    }
                }
                sub_matrix[i_sub][j_sub] = total;
            }
        }

        // Normalize rows
        for row in sub_matrix.iter_mut() {
            let sum: f64 = row.iter().sum();
            if sum > 0.0 {
                for elem in row.iter_mut() {
                    *elem /= sum;
                }
            }
        }

        TransitionProbabilityMatrix { matrix: sub_matrix }
    }

    /// Compose a full index from sub-system and other-system indices.
    fn compose_index(
        sub_val: usize,
        sub_qubits: &[usize],
        other_val: usize,
        other_qubits: &[usize],
        _total_qubits: usize,
    ) -> usize {
        let mut full_idx = 0usize;
        for (bit_pos, &qubit) in sub_qubits.iter().enumerate() {
            if (sub_val >> bit_pos) & 1 == 1 {
                full_idx |= 1 << qubit;
            }
        }
        for (bit_pos, &qubit) in other_qubits.iter().enumerate() {
            if (other_val >> bit_pos) & 1 == 1 {
                full_idx |= 1 << qubit;
            }
        }
        full_idx
    }

    /// Compute the tensor product of two TPMs.
    pub fn tensor_product(a: &TransitionProbabilityMatrix, b: &TransitionProbabilityMatrix) -> TransitionProbabilityMatrix {
        let da = a.dim();
        let db = b.dim();
        let d = da * db;
        let mut matrix = vec![vec![0.0; d]; d];

        for ia in 0..da {
            for ja in 0..da {
                for ib in 0..db {
                    for jb in 0..db {
                        matrix[ia * db + ib][ja * db + jb] = a.matrix[ia][ja] * b.matrix[ib][jb];
                    }
                }
            }
        }

        TransitionProbabilityMatrix { matrix }
    }
}

// ============================================================
// RESULT TYPES
// ============================================================

/// The minimum information partition and its associated information loss.
#[derive(Clone, Debug)]
pub struct MinimumInformationPartition {
    /// Qubit indices in each part of the partition.
    pub parts: Vec<Vec<usize>>,
    /// The information lost by this partition.
    pub information_loss: f64,
    /// Human-readable description of the partition type.
    pub partition_type: String,
}

/// Result of computing integrated information (Phi).
#[derive(Clone, Debug)]
pub struct PhiResult {
    /// The integrated information value.
    pub phi: f64,
    /// The partition achieving the minimum.
    pub mip: MinimumInformationPartition,
    /// Cause information component.
    pub cause_info: f64,
    /// Effect information component.
    pub effect_info: f64,
    /// Phi normalized to [0, 1] range: phi / max_possible_phi.
    pub normalized_phi: f64,
    /// Number of partitions that were evaluated.
    pub num_partitions_tested: usize,
}

/// A concept in the cause-effect structure (irreducible cause-effect repertoire).
#[derive(Clone, Debug)]
pub struct Concept {
    /// Qubit indices forming the mechanism.
    pub mechanism: Vec<usize>,
    /// Qubits in the cause purview.
    pub cause_purview: Vec<usize>,
    /// Qubits in the effect purview.
    pub effect_purview: Vec<usize>,
    /// Irreducible cause-effect information for this concept.
    pub phi: f64,
    /// Probability distribution over cause states.
    pub cause_repertoire: Vec<f64>,
    /// Probability distribution over effect states.
    pub effect_repertoire: Vec<f64>,
}

/// The complete cause-effect structure of a system.
#[derive(Clone, Debug)]
pub struct CauseEffectStructure {
    /// Set of concepts (irreducible cause-effect repertoires with phi > 0).
    pub concepts: Vec<Concept>,
    /// Integrated conceptual information (sum of concept phi values).
    pub phi: f64,
    /// Number of concepts found.
    pub num_concepts: usize,
}

// ============================================================
// LINEAR ALGEBRA HELPERS (inline, no external crates)
// ============================================================

/// Compute the density matrix rho = |psi><psi| from a state vector (row-major flat).
fn density_matrix_from_state(amplitudes: &[C64]) -> Vec<C64> {
    let d = amplitudes.len();
    let mut rho = vec![C64::new(0.0, 0.0); d * d];
    for i in 0..d {
        for j in 0..d {
            rho[i * d + j] = amplitudes[i] * amplitudes[j].conj();
        }
    }
    rho
}

/// Partial trace: given density matrix rho on n qubits, trace out complement of
/// `keep_qubits` and return the reduced density matrix.
///
/// rho is stored as flat row-major of dimension 2^n x 2^n.
fn partial_trace(rho: &[C64], n: usize, keep_qubits: &[usize]) -> Vec<C64> {
    let d_full = 1 << n;
    let n_keep = keep_qubits.len();
    let d_keep = 1 << n_keep;

    let trace_qubits: Vec<usize> = (0..n).filter(|q| !keep_qubits.contains(q)).collect();
    let n_trace = trace_qubits.len();
    let d_trace = 1 << n_trace;

    let mut reduced = vec![C64::new(0.0, 0.0); d_keep * d_keep];

    for i_keep in 0..d_keep {
        for j_keep in 0..d_keep {
            let mut sum = C64::new(0.0, 0.0);
            for t in 0..d_trace {
                let i_full = compose_full_index(i_keep, keep_qubits, t, &trace_qubits);
                let j_full = compose_full_index(j_keep, keep_qubits, t, &trace_qubits);
                if i_full < d_full && j_full < d_full {
                    sum += rho[i_full * d_full + j_full];
                }
            }
            reduced[i_keep * d_keep + j_keep] = sum;
        }
    }

    reduced
}

/// Compose a full-system index from subsystem indices.
fn compose_full_index(
    keep_val: usize,
    keep_qubits: &[usize],
    trace_val: usize,
    trace_qubits: &[usize],
) -> usize {
    let mut idx = 0usize;
    for (bit, &qubit) in keep_qubits.iter().enumerate() {
        if (keep_val >> bit) & 1 == 1 {
            idx |= 1 << qubit;
        }
    }
    for (bit, &qubit) in trace_qubits.iter().enumerate() {
        if (trace_val >> bit) & 1 == 1 {
            idx |= 1 << qubit;
        }
    }
    idx
}

/// Eigenvalue decomposition of a Hermitian matrix using Jacobi rotations.
///
/// Input: Hermitian matrix A of dimension d x d, stored as flat row-major Vec<C64>.
/// Output: real eigenvalues sorted in descending order.
///
/// The Jacobi method applies sequences of 2x2 rotations to drive off-diagonal
/// elements to zero. For Hermitian matrices this converges to a diagonal matrix
/// whose entries are the real eigenvalues.
fn hermitian_eigenvalues(matrix: &[C64], d: usize) -> Vec<f64> {
    if d == 0 {
        return Vec::new();
    }
    if d == 1 {
        return vec![matrix[0].re];
    }

    // Special case for 2x2 Hermitian matrix: analytic formula
    if d == 2 {
        return eigenvalues_2x2_hermitian(matrix);
    }

    // Copy matrix into mutable working storage
    let mut a = matrix.to_vec();

    for _sweep in 0..MAX_JACOBI_SWEEPS {
        // Compute the sum of off-diagonal magnitudes
        let mut off_diag_sum = 0.0f64;
        for i in 0..d {
            for j in (i + 1)..d {
                off_diag_sum += a[i * d + j].norm_sqr();
            }
        }
        if off_diag_sum < DEFAULT_PRECISION * DEFAULT_PRECISION {
            break;
        }

        // Threshold for small rotations
        let threshold = if _sweep < 4 {
            0.2 * off_diag_sum / (d * d) as f64
        } else {
            0.0
        };

        for p in 0..d {
            for q in (p + 1)..d {
                let apq = a[p * d + q];
                let g = apq.norm_sqr();

                if _sweep < 4 && g < threshold {
                    continue;
                }
                if g < ENTROPY_EPSILON * ENTROPY_EPSILON {
                    continue;
                }

                let app = a[p * d + p].re;
                let aqq = a[q * d + q].re;
                let h = aqq - app;

                // Compute rotation parameters for Hermitian Jacobi
                let apq_mag = apq.norm();
                if apq_mag < ENTROPY_EPSILON {
                    continue;
                }

                // Phase factor: apq = |apq| * e^{i*phi}
                let phase = if apq_mag > 0.0 {
                    apq / C64::new(apq_mag, 0.0)
                } else {
                    C64::new(1.0, 0.0)
                };

                let tau = h / (2.0 * apq_mag);
                let t = if tau.abs() > 1e15 {
                    // Very small rotation
                    1.0 / (2.0 * tau)
                } else {
                    let sign_tau = if tau >= 0.0 { 1.0 } else { -1.0 };
                    sign_tau / (tau.abs() + (1.0 + tau * tau).sqrt())
                };

                let c = 1.0 / (1.0 + t * t).sqrt();
                let s = t * c;

                // Apply the rotation: A' = G^dagger A G
                // where G is a Givens rotation in the (p,q) plane with phase
                let s_phase = C64::new(s, 0.0) * phase;
                let s_phase_conj = s_phase.conj();

                // Update diagonal elements
                a[p * d + p] = C64::new(app - t * apq_mag, 0.0);
                a[q * d + q] = C64::new(aqq + t * apq_mag, 0.0);
                a[p * d + q] = C64::new(0.0, 0.0);
                a[q * d + p] = C64::new(0.0, 0.0);

                // Update off-diagonal elements
                for r in 0..d {
                    if r == p || r == q {
                        continue;
                    }
                    let arp = a[r * d + p];
                    let arq = a[r * d + q];

                    let new_arp = C64::new(c, 0.0) * arp - s_phase_conj * arq;
                    let new_arq = s_phase * arp + C64::new(c, 0.0) * arq;

                    a[r * d + p] = new_arp;
                    a[p * d + r] = new_arp.conj();
                    a[r * d + q] = new_arq;
                    a[q * d + r] = new_arq.conj();
                }
            }
        }
    }

    // Extract eigenvalues from diagonal
    let mut eigenvalues: Vec<f64> = (0..d).map(|i| a[i * d + i].re).collect();
    eigenvalues.sort_by(|a, b| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));
    eigenvalues
}

/// Analytic eigenvalues for a 2x2 Hermitian matrix.
fn eigenvalues_2x2_hermitian(m: &[C64]) -> Vec<f64> {
    let a = m[0].re;
    let d = m[3].re;
    let b_sq = m[1].norm_sqr(); // |off-diagonal|^2
    let trace = a + d;
    let det = a * d - b_sq;
    let disc = (trace * trace - 4.0 * det).max(0.0).sqrt();
    let l1 = (trace + disc) / 2.0;
    let l2 = (trace - disc) / 2.0;
    if l1 >= l2 {
        vec![l1, l2]
    } else {
        vec![l2, l1]
    }
}

/// Von Neumann entropy S(rho) = -Tr(rho ln rho) = -sum_i lambda_i ln(lambda_i).
///
/// Uses natural log (nats). For bits, divide by ln(2).
fn von_neumann_entropy(rho: &[C64], d: usize) -> f64 {
    let eigenvalues = hermitian_eigenvalues(rho, d);
    let mut s = 0.0;
    for &lam in &eigenvalues {
        if lam > ENTROPY_EPSILON {
            s -= lam * lam.ln();
        }
    }
    s
}

/// Von Neumann entropy in bits (log base 2).
fn von_neumann_entropy_bits(rho: &[C64], d: usize) -> f64 {
    let eigenvalues = hermitian_eigenvalues(rho, d);
    let mut s = 0.0;
    for &lam in &eigenvalues {
        if lam > ENTROPY_EPSILON {
            s -= lam * lam.log2();
        }
    }
    s
}

/// Trace of a square matrix stored in flat row-major form.
fn matrix_trace(m: &[C64], d: usize) -> C64 {
    let mut tr = C64::new(0.0, 0.0);
    for i in 0..d {
        tr += m[i * d + i];
    }
    tr
}

/// L1 distance between two probability distributions (used as simplified EMD).
fn l1_distance(p: &[f64], q: &[f64]) -> f64 {
    p.iter()
        .zip(q.iter())
        .map(|(&a, &b)| (a - b).abs())
        .sum::<f64>()
        / 2.0
}

/// KL divergence D_KL(P || Q) = sum P(i) * ln(P(i)/Q(i)).
fn kl_divergence(p: &[f64], q: &[f64]) -> f64 {
    let mut kl = 0.0;
    for (&pi, &qi) in p.iter().zip(q.iter()) {
        if pi > ENTROPY_EPSILON {
            let qi_safe = qi.max(ENTROPY_EPSILON);
            kl += pi * (pi / qi_safe).ln();
        }
    }
    kl
}

/// Shannon entropy H(P) = -sum P(i) ln P(i).
fn shannon_entropy(p: &[f64]) -> f64 {
    let mut h = 0.0;
    for &pi in p {
        if pi > ENTROPY_EPSILON {
            h -= pi * pi.ln();
        }
    }
    h
}

/// Generate all non-trivial bipartitions of n elements.
/// Returns bitmasks where bit i indicates element i is in part A.
/// Excludes the empty partition and the full partition (and their complements
/// to avoid duplicates).
fn all_bipartitions(n: usize) -> Vec<usize> {
    let total = 1 << n;
    let mut masks = Vec::new();
    // Consider masks from 1 to total/2 (avoid duplicates via symmetry)
    for mask in 1..(total / 2) {
        masks.push(mask);
    }
    // Also include total/2 if n > 1 (the "balanced" split)
    if n > 1 {
        masks.push(total / 2);
    }
    masks
}

/// Generate all subsets of elements {0, 1, ..., n-1} of size >= 1.
fn all_nonempty_subsets(n: usize) -> Vec<Vec<usize>> {
    let total = 1 << n;
    let mut subsets = Vec::new();
    for mask in 1..total {
        let mut subset = Vec::new();
        for i in 0..n {
            if (mask >> i) & 1 == 1 {
                subset.push(i);
            }
        }
        subsets.push(subset);
    }
    subsets
}

// ============================================================
// QUANTUM IIT ANALYZER
// ============================================================

/// Main IIT analyzer for quantum systems.
///
/// Computes integrated information (Phi) and related quantities
/// for quantum states, using the formulation specified in the config.
pub struct QuantumIIT {
    /// Configuration parameters.
    config: IITConfig,
}

impl QuantumIIT {
    /// Create a new IIT analyzer with the given configuration.
    pub fn new(config: IITConfig) -> Self {
        QuantumIIT { config }
    }

    /// Compute integrated information Phi for a quantum state.
    ///
    /// Dispatches to the appropriate Phi version based on the configuration.
    pub fn compute_phi(&self, state: &QuantumState) -> PhiResult {
        let n = state.num_qubits;
        match self.config.phi_version {
            PhiVersion::Phi2_0 => self.compute_phi_2_0(state, n),
            PhiVersion::Phi3_0 => self.compute_phi_3_0(state, n),
            PhiVersion::PhiStar => self.compute_phi_star(state, n),
        }
    }

    /// Compute Phi from a precomputed transition probability matrix.
    pub fn compute_phi_from_tpm(&self, tpm: &TransitionProbabilityMatrix) -> PhiResult {
        let d = tpm.dim();
        let n = (d as f64).log2().round() as usize;
        self.compute_phi_2_0_from_tpm(tpm, n)
    }

    /// Compute the cause-effect structure (set of all concepts with phi > 0).
    pub fn cause_effect_structure(&self, state: &QuantumState) -> CauseEffectStructure {
        let n = state.num_qubits;
        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;

        let mut concepts = Vec::new();
        let mut total_phi = 0.0;

        // For each non-empty subset (mechanism), compute irreducible cause-effect info
        let subsets = all_nonempty_subsets(n);
        for mechanism in &subsets {
            let concept = self.compute_concept(&rho, d, n, mechanism);
            if concept.phi > self.config.precision {
                total_phi += concept.phi;
                concepts.push(concept);
            }
        }

        let num_concepts = concepts.len();
        CauseEffectStructure {
            concepts,
            phi: total_phi,
            num_concepts,
        }
    }

    /// Find the Minimum Information Partition of a quantum state.
    pub fn find_mip(&self, state: &QuantumState) -> MinimumInformationPartition {
        let result = self.compute_phi(state);
        result.mip
    }

    /// Compute the quantum mutual information I(A:B) for a given partition.
    ///
    /// I(A:B) = S(rho_A) + S(rho_B) - S(rho_AB)
    /// where S is the von Neumann entropy.
    pub fn mutual_information(&self, state: &QuantumState, partition: &Partition) -> f64 {
        let n = state.num_qubits;
        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;

        self.quantum_mutual_info_for_partition(&rho, d, n, partition)
    }

    /// Compute the intrinsic information of a quantum state.
    ///
    /// This is the total von Neumann entropy of the state, which measures
    /// the information content independent of any partition.
    pub fn intrinsic_information(&self, state: &QuantumState) -> f64 {
        let n = state.num_qubits;
        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;
        von_neumann_entropy(&rho, d)
    }

    /// Compute geometric Phi using quantum mutual information directly.
    ///
    /// The most natural quantum formulation: minimize I(A:B) over all
    /// bipartitions of the system.
    ///
    /// Phi_geo = min_{(A,B)} I(A:B) where I(A:B) = S(A) + S(B) - S(AB)
    pub fn quantum_phi_geometric(&self, state: &QuantumState) -> f64 {
        let n = state.num_qubits;
        if n < 2 {
            return 0.0;
        }

        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;

        let mut min_mi = f64::MAX;

        let masks = all_bipartitions(n);
        for &mask in &masks {
            let partition = Partition::from_bitmask(n, mask);
            let mi = self.quantum_mutual_info_for_partition(&rho, d, n, &partition);
            if mi < min_mi {
                min_mi = mi;
            }
        }

        if min_mi == f64::MAX {
            0.0
        } else {
            min_mi.max(0.0)
        }
    }

    // ----------------------------------------------------------------
    // PHI 2.0 IMPLEMENTATION
    // ----------------------------------------------------------------

    /// Phi 2.0: compare whole-system TPM to product of marginal TPMs.
    ///
    /// For each bipartition (A,B):
    ///   1. Compute marginal TPM_A and TPM_B
    ///   2. Compute product TPM_A tensor TPM_B
    ///   3. Distance = L1 distance between whole TPM and product TPM
    /// Phi = min over bipartitions of this distance.
    fn compute_phi_2_0(&self, _state: &QuantumState, n: usize) -> PhiResult {
        if n < 2 {
            return self.trivial_phi_result(n);
        }

        // Build TPM from a Hadamard-based unitary (representative evolution)
        let _d = 1 << n;
        let unitary = self.build_representative_unitary(n);
        let tpm = TransitionProbabilityMatrix::from_unitary(&unitary, 0.0);

        self.compute_phi_2_0_from_tpm(&tpm, n)
    }

    fn compute_phi_2_0_from_tpm(&self, tpm: &TransitionProbabilityMatrix, n: usize) -> PhiResult {
        if n < 2 {
            return self.trivial_phi_result(n);
        }

        let masks = all_bipartitions(n);
        let mut min_distance = f64::MAX;
        let mut best_mask = 1usize;
        let mut num_tested = 0;

        for &mask in &masks {
            let partition = Partition::from_bitmask(n, mask);
            let part_a = &partition.parts[0];
            let part_b = &partition.parts[1];

            if part_a.is_empty() || part_b.is_empty() {
                continue;
            }

            // Marginal TPMs
            let tpm_a = tpm.marginal_tpm(part_a, n);
            let tpm_b = tpm.marginal_tpm(part_b, n);

            // Product TPM
            let tpm_product = TransitionProbabilityMatrix::tensor_product(&tpm_a, &tpm_b);

            // L1 distance between flattened TPMs (simplified EMD)
            let dist = self.tpm_l1_distance(tpm, &tpm_product, n, &partition);

            num_tested += 1;
            if dist < min_distance {
                min_distance = dist;
                best_mask = mask;
            }
        }

        let best_partition = Partition::from_bitmask(n, best_mask);
        let phi = min_distance.max(0.0);
        let max_phi = (n as f64).ln().max(1.0);

        PhiResult {
            phi,
            mip: MinimumInformationPartition {
                parts: best_partition.parts,
                information_loss: phi,
                partition_type: "Phi2.0 bipartition (L1 distance)".to_string(),
            },
            cause_info: phi / 2.0,
            effect_info: phi / 2.0,
            normalized_phi: (phi / max_phi).min(1.0),
            num_partitions_tested: num_tested,
        }
    }

    /// Compute L1 distance between whole TPM and product TPM.
    ///
    /// Since marginal TPMs may have different dimensions, we compare
    /// row-by-row using the reordered product structure.
    fn tpm_l1_distance(
        &self,
        whole: &TransitionProbabilityMatrix,
        product: &TransitionProbabilityMatrix,
        _n: usize,
        _partition: &Partition,
    ) -> f64 {
        let d_whole = whole.dim();
        let d_product = product.dim();

        // If dimensions match, direct L1
        if d_whole == d_product {
            let mut total = 0.0;
            for i in 0..d_whole {
                total += l1_distance(&whole.matrix[i], &product.matrix[i]);
            }
            return total / d_whole as f64;
        }

        // Dimensions differ: use row-averaged L1 on the whole TPM vs uniform baseline
        let uniform = 1.0 / d_whole as f64;
        let uniform_row = vec![uniform; d_whole];
        let mut total = 0.0;
        for i in 0..d_whole {
            total += l1_distance(&whole.matrix[i], &uniform_row);
        }
        total / d_whole as f64
    }

    // ----------------------------------------------------------------
    // PHI 3.0 IMPLEMENTATION
    // ----------------------------------------------------------------

    /// Phi 3.0: Minimum Information Partition using cause-effect info.
    ///
    /// For each bipartition (A,B):
    ///   1. Compute cause-effect information for the whole system
    ///   2. Compute cause-effect information for the "cut" system
    ///   3. Information loss = whole - cut
    /// Phi = min information loss over all bipartitions (the MIP).
    fn compute_phi_3_0(&self, state: &QuantumState, n: usize) -> PhiResult {
        if n < 2 {
            return self.trivial_phi_result(n);
        }

        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;

        // Whole-system cause-effect information
        let whole_info = self.whole_system_info(&rho, d, n);

        let masks = all_bipartitions(n);
        let mut min_loss = f64::MAX;
        let mut best_mask = 1usize;
        let mut num_tested = 0;

        for &mask in &masks {
            let partition = Partition::from_bitmask(n, mask);

            if partition.parts[0].is_empty() || partition.parts[1].is_empty() {
                continue;
            }

            // "Cut" information: sum of independent partition entropies
            let cut_info = self.cut_system_info(&rho, d, n, &partition);
            let loss = (whole_info - cut_info).max(0.0);

            num_tested += 1;
            if loss < min_loss {
                min_loss = loss;
                best_mask = mask;
            }
        }

        let best_partition = Partition::from_bitmask(n, best_mask);
        let phi = min_loss.max(0.0);

        // Approximate cause/effect split
        let cause_info = phi * 0.5;
        let effect_info = phi * 0.5;
        let max_phi = (n as f64) * 2.0_f64.ln();

        PhiResult {
            phi,
            mip: MinimumInformationPartition {
                parts: best_partition.parts,
                information_loss: phi,
                partition_type: "Phi3.0 MIP (cause-effect)".to_string(),
            },
            cause_info,
            effect_info,
            normalized_phi: (phi / max_phi).min(1.0),
            num_partitions_tested: num_tested,
        }
    }

    /// Whole-system cause-effect information.
    ///
    /// Measures total correlation: sum of subsystem entropies minus joint entropy.
    /// For a pure state, S(rho) = 0, so this reduces to sum of subsystem entropies.
    fn whole_system_info(&self, rho: &[C64], d: usize, n: usize) -> f64 {
        let s_total = von_neumann_entropy(rho, d);

        // Sum of single-qubit entropies
        let mut s_parts = 0.0;
        for q in 0..n {
            let rho_q = partial_trace(rho, n, &[q]);
            s_parts += von_neumann_entropy(&rho_q, 2);
        }

        // Total correlation = sum(S_i) - S(whole)
        s_parts - s_total
    }

    /// Cut-system cause-effect information.
    ///
    /// For a bipartition (A,B), the cut system treats A and B independently.
    /// The cut info is the sum of within-partition correlations.
    fn cut_system_info(&self, rho: &[C64], _d: usize, n: usize, partition: &Partition) -> f64 {
        let mut cut_info = 0.0;

        for part in &partition.parts {
            if part.len() <= 1 {
                // Single qubit has zero internal correlation
                continue;
            }

            let rho_part = partial_trace(rho, n, part);
            let d_part = 1 << part.len();
            let s_part = von_neumann_entropy(&rho_part, d_part);

            // Sum of individual entropies within this part
            let mut s_individuals = 0.0;
            for &q in part {
                let rho_q = partial_trace(rho, n, &[q]);
                s_individuals += von_neumann_entropy(&rho_q, 2);
            }

            cut_info += s_individuals - s_part;
        }

        cut_info
    }

    // ----------------------------------------------------------------
    // PHI STAR IMPLEMENTATION
    // ----------------------------------------------------------------

    /// Phi* (practical approximation): minimum mutual information over bipartitions.
    ///
    /// Phi* = min_{(A,B)} I(A;B)
    /// where I(A;B) = S(A) + S(B) - S(AB) is the quantum mutual information.
    fn compute_phi_star(&self, state: &QuantumState, n: usize) -> PhiResult {
        if n < 2 {
            return self.trivial_phi_result(n);
        }

        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let d = 1 << n;

        let masks = all_bipartitions(n);
        let mut min_mi = f64::MAX;
        let mut best_mask = 1usize;
        let mut num_tested = 0;

        for &mask in &masks {
            let partition = Partition::from_bitmask(n, mask);

            if partition.parts[0].is_empty() || partition.parts[1].is_empty() {
                continue;
            }

            let mi = self.quantum_mutual_info_for_partition(&rho, d, n, &partition);
            num_tested += 1;

            if mi < min_mi {
                min_mi = mi;
                best_mask = mask;
            }
        }

        let best_partition = Partition::from_bitmask(n, best_mask);
        let phi = min_mi.max(0.0);
        let max_phi = (n as f64) * 2.0_f64.ln();

        PhiResult {
            phi,
            mip: MinimumInformationPartition {
                parts: best_partition.parts,
                information_loss: phi,
                partition_type: "PhiStar (mutual information)".to_string(),
            },
            cause_info: phi / 2.0,
            effect_info: phi / 2.0,
            normalized_phi: (phi / max_phi).min(1.0),
            num_partitions_tested: num_tested,
        }
    }

    // ----------------------------------------------------------------
    // HELPERS
    // ----------------------------------------------------------------

    /// Quantum mutual information I(A:B) = S(A) + S(B) - S(AB).
    fn quantum_mutual_info_for_partition(
        &self,
        rho: &[C64],
        d: usize,
        n: usize,
        partition: &Partition,
    ) -> f64 {
        if partition.parts.len() < 2 {
            return 0.0;
        }

        let part_a = &partition.parts[0];
        let part_b = &partition.parts[1];

        // S(A)
        let rho_a = partial_trace(rho, n, part_a);
        let d_a = 1 << part_a.len();
        let s_a = von_neumann_entropy(&rho_a, d_a);

        // S(B)
        let rho_b = partial_trace(rho, n, part_b);
        let d_b = 1 << part_b.len();
        let s_b = von_neumann_entropy(&rho_b, d_b);

        // S(AB) - entropy of the joint system
        // If the partition covers all qubits, S(AB) = S(rho)
        let s_ab = if part_a.len() + part_b.len() == n {
            von_neumann_entropy(rho, d)
        } else {
            let mut all_qubits: Vec<usize> = part_a.clone();
            all_qubits.extend_from_slice(part_b);
            let rho_ab = partial_trace(rho, n, &all_qubits);
            let d_ab = 1 << all_qubits.len();
            von_neumann_entropy(&rho_ab, d_ab)
        };

        // I(A:B) = S(A) + S(B) - S(AB)
        let mi = s_a + s_b - s_ab;
        mi.max(0.0) // Clamp to non-negative (numerical safety)
    }

    /// Compute a concept for a given mechanism (subset of qubits).
    fn compute_concept(
        &self,
        rho: &[C64],
        d: usize,
        n: usize,
        mechanism: &[usize],
    ) -> Concept {
        let complement: Vec<usize> = (0..n).filter(|q| !mechanism.contains(q)).collect();

        if complement.is_empty() {
            // Mechanism is the entire system -- no partition possible
            return Concept {
                mechanism: mechanism.to_vec(),
                cause_purview: mechanism.to_vec(),
                effect_purview: mechanism.to_vec(),
                phi: 0.0,
                cause_repertoire: vec![1.0 / (1 << mechanism.len()) as f64; 1 << mechanism.len()],
                effect_repertoire: vec![1.0 / (1 << mechanism.len()) as f64; 1 << mechanism.len()],
            };
        }

        // Cause repertoire: reduced state of mechanism
        let rho_m = partial_trace(rho, n, mechanism);
        let d_m = 1 << mechanism.len();
        let cause_repertoire: Vec<f64> = (0..d_m)
            .map(|i| rho_m[i * d_m + i].re.max(0.0))
            .collect();

        // Effect repertoire: reduced state of complement conditioned on mechanism
        let rho_c = partial_trace(rho, n, &complement);
        let d_c = 1 << complement.len();
        let effect_repertoire: Vec<f64> = (0..d_c)
            .map(|i| rho_c[i * d_c + i].re.max(0.0))
            .collect();

        // Compute irreducible information for this concept
        // phi = mutual information between mechanism and its complement
        let partition = Partition {
            parts: vec![mechanism.to_vec(), complement.clone()],
        };
        let phi = self.quantum_mutual_info_for_partition(rho, d, n, &partition);

        // Best cause/effect purview is the complement for a bipartite system
        Concept {
            mechanism: mechanism.to_vec(),
            cause_purview: complement.clone(),
            effect_purview: complement,
            phi,
            cause_repertoire,
            effect_repertoire,
        }
    }

    /// Build a representative unitary for the system (for Phi 2.0 TPM construction).
    ///
    /// Uses a product of CNOT-like and Hadamard gates to create entangling dynamics.
    fn build_representative_unitary(&self, n: usize) -> Vec<Vec<C64>> {
        let d = 1 << n;
        // Start with identity
        let mut unitary = vec![vec![C64::new(0.0, 0.0); d]; d];
        for i in 0..d {
            unitary[i][i] = C64::new(1.0, 0.0);
        }

        // Apply Hadamard to qubit 0
        let h_factor = 1.0 / 2.0_f64.sqrt();
        let mut h_unitary = vec![vec![C64::new(0.0, 0.0); d]; d];
        for i in 0..d {
            for j in 0..d {
                // Hadamard on qubit 0: flips bit 0, with sign factor
                let i0 = i & 1;
                let j0 = j & 1;
                let i_rest = i >> 1;
                let j_rest = j >> 1;
                if i_rest == j_rest {
                    let h_elem = match (i0, j0) {
                        (0, 0) => h_factor,
                        (0, 1) => h_factor,
                        (1, 0) => h_factor,
                        (1, 1) => -h_factor,
                        _ => 0.0,
                    };
                    h_unitary[i][j] = C64::new(h_elem, 0.0);
                }
            }
        }
        unitary = mat_mul_square(&h_unitary, &unitary, d);

        // Apply CNOT(0, 1) if n >= 2
        if n >= 2 {
            let mut cnot = vec![vec![C64::new(0.0, 0.0); d]; d];
            for i in 0..d {
                let bit0 = (i >> 0) & 1;
                let bit1 = (i >> 1) & 1;
                let new_bit1 = bit0 ^ bit1;
                let j = (i & !(1 << 1)) | (new_bit1 << 1);
                cnot[j][i] = C64::new(1.0, 0.0);
            }
            unitary = mat_mul_square(&cnot, &unitary, d);
        }

        unitary
    }

    /// Return a trivial PhiResult for systems too small to partition.
    fn trivial_phi_result(&self, n: usize) -> PhiResult {
        PhiResult {
            phi: 0.0,
            mip: MinimumInformationPartition {
                parts: vec![(0..n).collect()],
                information_loss: 0.0,
                partition_type: "trivial (no partition possible)".to_string(),
            },
            cause_info: 0.0,
            effect_info: 0.0,
            normalized_phi: 0.0,
            num_partitions_tested: 0,
        }
    }
}

/// Square matrix multiplication C = A * B (both d x d, stored as Vec<Vec<C64>>).
fn mat_mul_square(a: &[Vec<C64>], b: &[Vec<C64>], d: usize) -> Vec<Vec<C64>> {
    let mut c = vec![vec![C64::new(0.0, 0.0); d]; d];
    for i in 0..d {
        for k in 0..d {
            if a[i][k].norm_sqr() < ENTROPY_EPSILON * ENTROPY_EPSILON {
                continue;
            }
            for j in 0..d {
                c[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    c
}

// ============================================================
// TESTS
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{GateOperations, QuantumState};

    /// Helper: create a Bell state (|00> + |11>) / sqrt(2)
    fn bell_state() -> QuantumState {
        let mut state = QuantumState::new(2);
        GateOperations::h(&mut state, 0);
        GateOperations::cnot(&mut state, 0, 1);
        state
    }

    /// Helper: create a product state |00>
    fn product_state_2q() -> QuantumState {
        QuantumState::new(2)
    }

    /// Helper: create a GHZ state (|000> + |111>) / sqrt(2)
    fn ghz_state_3q() -> QuantumState {
        let mut state = QuantumState::new(3);
        GateOperations::h(&mut state, 0);
        GateOperations::cnot(&mut state, 0, 1);
        GateOperations::cnot(&mut state, 0, 2);
        state
    }

    // ----------------------------------------------------------
    // 1. Config builder
    // ----------------------------------------------------------
    #[test]
    fn test_config_builder() {
        let cfg = IITConfig::default();
        assert_eq!(cfg.num_qubits, 4);
        assert_eq!(cfg.phi_version, PhiVersion::Phi3_0);
        assert_eq!(cfg.partition_strategy, PartitionStrategy::BipartitionSearch);
        assert!((cfg.precision - 1e-8).abs() < 1e-15);

        let cfg2 = IITConfig::new(6)
            .with_phi_version(PhiVersion::PhiStar)
            .with_partition_strategy(PartitionStrategy::Greedy)
            .with_precision(1e-10);
        assert_eq!(cfg2.num_qubits, 6);
        assert_eq!(cfg2.phi_version, PhiVersion::PhiStar);
        assert_eq!(cfg2.partition_strategy, PartitionStrategy::Greedy);
        assert!((cfg2.precision - 1e-10).abs() < 1e-15);
    }

    // ----------------------------------------------------------
    // 2. Phi = 0 for product state
    // ----------------------------------------------------------
    #[test]
    fn test_phi_product_state_zero() {
        let state = product_state_2q();
        let config = IITConfig::new(2).with_phi_version(PhiVersion::PhiStar);
        let iit = QuantumIIT::new(config);
        let result = iit.compute_phi(&state);
        assert!(
            result.phi < 1e-6,
            "Product state should have Phi ~ 0, got {}",
            result.phi
        );
    }

    // ----------------------------------------------------------
    // 3. Phi > 0 for Bell state
    // ----------------------------------------------------------
    #[test]
    fn test_phi_bell_state_positive() {
        let state = bell_state();
        let config = IITConfig::new(2).with_phi_version(PhiVersion::PhiStar);
        let iit = QuantumIIT::new(config);
        let result = iit.compute_phi(&state);
        assert!(
            result.phi > 0.1,
            "Bell state should have significant Phi, got {}",
            result.phi
        );
    }

    // ----------------------------------------------------------
    // 4. GHZ state has high Phi
    // ----------------------------------------------------------
    #[test]
    fn test_phi_ghz_high() {
        let state = ghz_state_3q();
        let config = IITConfig::new(3).with_phi_version(PhiVersion::PhiStar);
        let iit = QuantumIIT::new(config);
        let result = iit.compute_phi(&state);
        assert!(
            result.phi > 0.1,
            "GHZ state should have high Phi, got {}",
            result.phi
        );
    }

    // ----------------------------------------------------------
    // 5. TPM from unitary is stochastic
    // ----------------------------------------------------------
    #[test]
    fn test_tpm_from_unitary() {
        // 1-qubit Hadamard
        let h = 1.0 / 2.0_f64.sqrt();
        let unitary = vec![
            vec![C64::new(h, 0.0), C64::new(h, 0.0)],
            vec![C64::new(h, 0.0), C64::new(-h, 0.0)],
        ];
        let tpm = TransitionProbabilityMatrix::from_unitary(&unitary, 0.0);

        assert!(tpm.is_stochastic(1e-10), "TPM from unitary must be stochastic");
        assert_eq!(tpm.dim(), 2);

        // Hadamard: |0> -> (|0> + |1>)/sqrt(2) so TPM[0][0] = TPM[0][1] = 0.5
        assert!((tpm.matrix[0][0] - 0.5).abs() < 1e-10);
        assert!((tpm.matrix[0][1] - 0.5).abs() < 1e-10);
    }

    // ----------------------------------------------------------
    // 6. Noisy TPM is more uniform
    // ----------------------------------------------------------
    #[test]
    fn test_tpm_with_noise() {
        // Identity unitary
        let unitary = vec![
            vec![C64::new(1.0, 0.0), C64::new(0.0, 0.0)],
            vec![C64::new(0.0, 0.0), C64::new(1.0, 0.0)],
        ];
        let tpm_clean = TransitionProbabilityMatrix::from_unitary(&unitary, 0.0);
        let tpm_noisy = TransitionProbabilityMatrix::from_unitary(&unitary, 0.5);

        assert!(tpm_clean.is_stochastic(1e-10));
        assert!(tpm_noisy.is_stochastic(1e-10));

        // Clean identity: TPM[0][0] = 1.0
        assert!((tpm_clean.matrix[0][0] - 1.0).abs() < 1e-10);

        // With 50% noise: TPM[0][0] = 0.5 * 1.0 + 0.5 * 0.5 = 0.75
        assert!((tpm_noisy.matrix[0][0] - 0.75).abs() < 1e-10);
        // TPM[0][1] = 0.5 * 0.0 + 0.5 * 0.5 = 0.25
        assert!((tpm_noisy.matrix[0][1] - 0.25).abs() < 1e-10);
    }

    // ----------------------------------------------------------
    // 7. MIP is trivial for product state
    // ----------------------------------------------------------
    #[test]
    fn test_mip_product_state() {
        let state = product_state_2q();
        let config = IITConfig::new(2).with_phi_version(PhiVersion::PhiStar);
        let iit = QuantumIIT::new(config);
        let mip = iit.find_mip(&state);

        // For a product state, any partition has near-zero information loss
        assert!(
            mip.information_loss < 1e-6,
            "Product state MIP should have near-zero info loss, got {}",
            mip.information_loss
        );
    }

    // ----------------------------------------------------------
    // 8. MIP is non-trivial for Bell state
    // ----------------------------------------------------------
    #[test]
    fn test_mip_bell_state() {
        let state = bell_state();
        let config = IITConfig::new(2).with_phi_version(PhiVersion::PhiStar);
        let iit = QuantumIIT::new(config);
        let mip = iit.find_mip(&state);

        // For a Bell state, the only bipartition ({0}, {1}) has significant info loss
        assert!(
            mip.information_loss > 0.1,
            "Bell state MIP should have significant info loss, got {}",
            mip.information_loss
        );
        assert!(
            mip.parts.len() >= 2,
            "MIP should have at least 2 parts"
        );
    }

    // ----------------------------------------------------------
    // 9. Mutual information = 0 for product state
    // ----------------------------------------------------------
    #[test]
    fn test_mutual_information_independent() {
        let state = product_state_2q();
        let config = IITConfig::new(2);
        let iit = QuantumIIT::new(config);
        let partition = Partition::from_bitmask(2, 1); // {0} | {1}

        let mi = iit.mutual_information(&state, &partition);
        assert!(
            mi < 1e-6,
            "Product state should have MI ~ 0, got {}",
            mi
        );
    }

    // ----------------------------------------------------------
    // 10. Mutual information > 0 for Bell state
    // ----------------------------------------------------------
    #[test]
    fn test_mutual_information_bell() {
        let state = bell_state();
        let config = IITConfig::new(2);
        let iit = QuantumIIT::new(config);
        let partition = Partition::from_bitmask(2, 1); // {0} | {1}

        let mi = iit.mutual_information(&state, &partition);
        assert!(
            mi > 0.5,
            "Bell state should have significant MI, got {}",
            mi
        );
        // For Bell state, MI should be approximately 2 * ln(2)
        let expected = 2.0 * 2.0_f64.ln();
        assert!(
            (mi - expected).abs() < 0.2,
            "Bell state MI should be close to 2*ln(2) = {:.4}, got {:.4}",
            expected,
            mi
        );
    }

    // ----------------------------------------------------------
    // 11. Partial trace preserves trace
    // ----------------------------------------------------------
    #[test]
    fn test_partial_trace() {
        let state = bell_state();
        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let n = 2;
        let d = 4;

        // Full trace should be 1
        let tr_full = matrix_trace(&rho, d);
        assert!(
            (tr_full.re - 1.0).abs() < 1e-10,
            "Full density matrix trace should be 1, got {}",
            tr_full.re
        );

        // Partial trace over qubit 1 (keep qubit 0)
        let rho_0 = partial_trace(&rho, n, &[0]);
        let tr_0 = matrix_trace(&rho_0, 2);
        assert!(
            (tr_0.re - 1.0).abs() < 1e-10,
            "Reduced density matrix trace should be 1, got {}",
            tr_0.re
        );

        // Partial trace over qubit 0 (keep qubit 1)
        let rho_1 = partial_trace(&rho, n, &[1]);
        let tr_1 = matrix_trace(&rho_1, 2);
        assert!(
            (tr_1.re - 1.0).abs() < 1e-10,
            "Reduced density matrix trace should be 1, got {}",
            tr_1.re
        );

        // For Bell state, reduced state should be maximally mixed: rho = I/2
        assert!(
            (rho_0[0].re - 0.5).abs() < 1e-10,
            "Bell state reduced rho[0][0] should be 0.5, got {}",
            rho_0[0].re
        );
        assert!(
            (rho_0[3].re - 0.5).abs() < 1e-10,
            "Bell state reduced rho[1][1] should be 0.5, got {}",
            rho_0[3].re
        );
    }

    // ----------------------------------------------------------
    // 12. Von Neumann entropy = 0 for pure state
    // ----------------------------------------------------------
    #[test]
    fn test_von_neumann_entropy_pure() {
        // |0> state: rho = |0><0|
        let rho = vec![
            C64::new(1.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
        ];
        let s = von_neumann_entropy(&rho, 2);
        assert!(
            s.abs() < 1e-8,
            "Pure state should have S = 0, got {}",
            s
        );

        // Bell state (global pure state)
        let state = bell_state();
        let amps = state.amplitudes_ref();
        let rho_bell = density_matrix_from_state(amps);
        let s_bell = von_neumann_entropy(&rho_bell, 4);
        assert!(
            s_bell.abs() < 1e-8,
            "Pure Bell state should have S = 0, got {}",
            s_bell
        );
    }

    // ----------------------------------------------------------
    // 13. Von Neumann entropy = ln(D) for maximally mixed
    // ----------------------------------------------------------
    #[test]
    fn test_von_neumann_entropy_maximally_mixed() {
        // Maximally mixed 2x2: rho = I/2
        let rho = vec![
            C64::new(0.5, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.5, 0.0),
        ];
        let s = von_neumann_entropy(&rho, 2);
        let expected = 2.0_f64.ln(); // ln(2)
        assert!(
            (s - expected).abs() < 1e-8,
            "Maximally mixed 2x2 should have S = ln(2) = {:.6}, got {:.6}",
            expected,
            s
        );

        // Maximally mixed 4x4: rho = I/4
        let mut rho4 = vec![C64::new(0.0, 0.0); 16];
        for i in 0..4 {
            rho4[i * 4 + i] = C64::new(0.25, 0.0);
        }
        let s4 = von_neumann_entropy(&rho4, 4);
        let expected4 = 4.0_f64.ln(); // ln(4) = 2*ln(2)
        assert!(
            (s4 - expected4).abs() < 1e-8,
            "Maximally mixed 4x4 should have S = ln(4) = {:.6}, got {:.6}",
            expected4,
            s4
        );
    }

    // ----------------------------------------------------------
    // 14. Phi* correlates with Phi 3.0
    // ----------------------------------------------------------
    #[test]
    fn test_phi_star_approximation() {
        let state = bell_state();

        let config_3 = IITConfig::new(2).with_phi_version(PhiVersion::Phi3_0);
        let iit_3 = QuantumIIT::new(config_3);
        let phi_3 = iit_3.compute_phi(&state);

        let config_star = IITConfig::new(2).with_phi_version(PhiVersion::PhiStar);
        let iit_star = QuantumIIT::new(config_star);
        let phi_star = iit_star.compute_phi(&state);

        // Both should be positive for the Bell state
        assert!(phi_3.phi > 0.0, "Phi 3.0 should be positive for Bell state");
        assert!(
            phi_star.phi > 0.0,
            "Phi* should be positive for Bell state"
        );

        // Both should agree on product state being zero
        let product = product_state_2q();
        let phi_3_prod = iit_3.compute_phi(&product);
        let phi_star_prod = iit_star.compute_phi(&product);

        assert!(phi_3_prod.phi < 1e-6, "Phi 3.0 should be ~0 for product state");
        assert!(phi_star_prod.phi < 1e-6, "Phi* should be ~0 for product state");
    }

    // ----------------------------------------------------------
    // 15. Cause-effect structure has concepts for entangled state
    // ----------------------------------------------------------
    #[test]
    fn test_cause_effect_structure() {
        let state = bell_state();
        let config = IITConfig::new(2);
        let iit = QuantumIIT::new(config);

        let ces = iit.cause_effect_structure(&state);
        assert!(
            ces.num_concepts > 0,
            "Bell state should have at least one concept, got {}",
            ces.num_concepts
        );
        assert!(
            ces.phi > 0.0,
            "CES phi should be positive for Bell state, got {}",
            ces.phi
        );

        // Verify concept structure
        for concept in &ces.concepts {
            assert!(
                !concept.mechanism.is_empty(),
                "Concept mechanism should not be empty"
            );
            assert!(
                concept.phi > 0.0,
                "Concept phi should be positive"
            );
            assert!(
                !concept.cause_repertoire.is_empty(),
                "Cause repertoire should not be empty"
            );
            assert!(
                !concept.effect_repertoire.is_empty(),
                "Effect repertoire should not be empty"
            );
        }

        // Product state should have zero or near-zero concepts
        let product = product_state_2q();
        let ces_prod = iit.cause_effect_structure(&product);
        assert!(
            ces_prod.phi < 1e-6,
            "Product state CES phi should be ~0, got {}",
            ces_prod.phi
        );
    }

    // ----------------------------------------------------------
    // 16. Geometric Phi > 0 for Bell state
    // ----------------------------------------------------------
    #[test]
    fn test_geometric_phi_bell() {
        let state = bell_state();
        let config = IITConfig::new(2);
        let iit = QuantumIIT::new(config);

        let phi_geo = iit.quantum_phi_geometric(&state);
        assert!(
            phi_geo > 0.5,
            "Geometric Phi should be significant for Bell state, got {}",
            phi_geo
        );

        // For product state, geometric Phi should be ~0
        let product = product_state_2q();
        let phi_geo_prod = iit.quantum_phi_geometric(&product);
        assert!(
            phi_geo_prod < 1e-6,
            "Geometric Phi should be ~0 for product state, got {}",
            phi_geo_prod
        );
    }

    // ----------------------------------------------------------
    // Extra: Partition validity
    // ----------------------------------------------------------
    #[test]
    fn test_partition_validity() {
        let p = Partition::from_bitmask(4, 0b0101); // {0,2} | {1,3}
        assert!(p.is_valid(4));
        assert_eq!(p.parts[0], vec![0, 2]);
        assert_eq!(p.parts[1], vec![1, 3]);
        assert_eq!(p.total_qubits(), 4);

        let atomic = Partition::atomic(3);
        assert!(atomic.is_valid(3));
        assert_eq!(atomic.parts.len(), 3);
    }

    // ----------------------------------------------------------
    // Extra: Hermitian eigenvalue solver correctness
    // ----------------------------------------------------------
    #[test]
    fn test_hermitian_eigenvalues_identity() {
        // 2x2 identity matrix: eigenvalues should be {1, 1}
        let id = vec![
            C64::new(1.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(1.0, 0.0),
        ];
        let eigs = hermitian_eigenvalues(&id, 2);
        assert_eq!(eigs.len(), 2);
        for &e in &eigs {
            assert!(
                (e - 1.0).abs() < 1e-10,
                "Identity eigenvalue should be 1, got {}",
                e
            );
        }
    }

    #[test]
    fn test_hermitian_eigenvalues_pauli_z() {
        // Pauli Z: diag(1, -1)
        let z = vec![
            C64::new(1.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(-1.0, 0.0),
        ];
        let eigs = hermitian_eigenvalues(&z, 2);
        assert!((eigs[0] - 1.0).abs() < 1e-10);
        assert!((eigs[1] - (-1.0)).abs() < 1e-10);
    }

    #[test]
    fn test_hermitian_eigenvalues_pauli_x() {
        // Pauli X: [[0,1],[1,0]], eigenvalues +1, -1
        let x = vec![
            C64::new(0.0, 0.0),
            C64::new(1.0, 0.0),
            C64::new(1.0, 0.0),
            C64::new(0.0, 0.0),
        ];
        let eigs = hermitian_eigenvalues(&x, 2);
        assert!((eigs[0] - 1.0).abs() < 1e-10, "Pauli X eigenvalue 0: {}", eigs[0]);
        assert!((eigs[1] - (-1.0)).abs() < 1e-10, "Pauli X eigenvalue 1: {}", eigs[1]);
    }

    // ----------------------------------------------------------
    // Extra: Phi 2.0 from TPM
    // ----------------------------------------------------------
    #[test]
    fn test_phi_2_0_from_tpm() {
        let config = IITConfig::new(2).with_phi_version(PhiVersion::Phi2_0);
        let iit = QuantumIIT::new(config);

        // Build a simple 2-qubit Hadamard + CNOT unitary
        let h = 1.0 / 2.0_f64.sqrt();
        // H tensor I, then CNOT
        let mut state = QuantumState::new(2);
        GateOperations::h(&mut state, 0);
        GateOperations::cnot(&mut state, 0, 1);

        let result = iit.compute_phi(&state);
        // Just verify it runs and returns reasonable values
        assert!(result.phi >= 0.0, "Phi 2.0 should be non-negative");
        assert!(result.num_partitions_tested > 0);
    }

    // ----------------------------------------------------------
    // Extra: Intrinsic information
    // ----------------------------------------------------------
    #[test]
    fn test_intrinsic_information() {
        let config = IITConfig::new(2);
        let iit = QuantumIIT::new(config);

        // Pure state has zero intrinsic information (S = 0)
        let product = product_state_2q();
        let info = iit.intrinsic_information(&product);
        assert!(
            info.abs() < 1e-8,
            "Pure state intrinsic information should be ~0, got {}",
            info
        );
    }

    // ----------------------------------------------------------
    // Extra: TPM from quantum channel
    // ----------------------------------------------------------
    #[test]
    fn test_tpm_from_quantum_channel() {
        // Identity channel: single Kraus op = I
        let kraus_i = vec![
            vec![C64::new(1.0, 0.0), C64::new(0.0, 0.0)],
            vec![C64::new(0.0, 0.0), C64::new(1.0, 0.0)],
        ];
        let channel = vec![kraus_i];
        let tpm = TransitionProbabilityMatrix::from_quantum_channel(&channel);

        assert!(tpm.is_stochastic(1e-10));
        // Identity channel: TPM should be identity
        assert!((tpm.matrix[0][0] - 1.0).abs() < 1e-10);
        assert!((tpm.matrix[0][1]).abs() < 1e-10);
        assert!((tpm.matrix[1][0]).abs() < 1e-10);
        assert!((tpm.matrix[1][1] - 1.0).abs() < 1e-10);
    }

    // ----------------------------------------------------------
    // Extra: Normalized phi is in [0, 1]
    // ----------------------------------------------------------
    #[test]
    fn test_normalized_phi_range() {
        for version in &[PhiVersion::Phi2_0, PhiVersion::Phi3_0, PhiVersion::PhiStar] {
            let state = bell_state();
            let config = IITConfig::new(2).with_phi_version(*version);
            let iit = QuantumIIT::new(config);
            let result = iit.compute_phi(&state);

            assert!(
                result.normalized_phi >= 0.0 && result.normalized_phi <= 1.0,
                "Normalized phi should be in [0,1] for {:?}, got {}",
                version,
                result.normalized_phi
            );
        }
    }

    // ----------------------------------------------------------
    // Extra: 3-qubit partial trace consistency
    // ----------------------------------------------------------
    #[test]
    fn test_partial_trace_3q() {
        let state = ghz_state_3q();
        let amps = state.amplitudes_ref();
        let rho = density_matrix_from_state(amps);
        let n = 3;

        // Trace out qubit 2, keep {0, 1}
        let rho_01 = partial_trace(&rho, n, &[0, 1]);
        let tr_01 = matrix_trace(&rho_01, 4);
        assert!(
            (tr_01.re - 1.0).abs() < 1e-10,
            "Tr(rho_01) should be 1, got {}",
            tr_01.re
        );

        // For GHZ: rho_{01} = (|00><00| + |11><11|) / 2
        assert!(
            (rho_01[0].re - 0.5).abs() < 1e-10,
            "GHZ rho_01[0][0] should be 0.5"
        );
        assert!(
            (rho_01[15].re - 0.5).abs() < 1e-10,
            "GHZ rho_01[3][3] should be 0.5"
        );

        // Single-qubit reduced state of GHZ should also be maximally mixed
        let rho_0 = partial_trace(&rho, n, &[0]);
        assert!((rho_0[0].re - 0.5).abs() < 1e-10);
        assert!((rho_0[3].re - 0.5).abs() < 1e-10);
    }

    // ----------------------------------------------------------
    // Extra: Von Neumann entropy in bits
    // ----------------------------------------------------------
    #[test]
    fn test_von_neumann_entropy_bits() {
        // Maximally mixed 2x2: S = 1 bit
        let rho = vec![
            C64::new(0.5, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.0, 0.0),
            C64::new(0.5, 0.0),
        ];
        let s = von_neumann_entropy_bits(&rho, 2);
        assert!(
            (s - 1.0).abs() < 1e-8,
            "Maximally mixed 2x2 entropy should be 1 bit, got {}",
            s
        );
    }
}
