//! Dispersive Readout Simulation for Superconducting Qubits
//!
//! Models the dispersive readout process used in transmon-based quantum
//! processors. In the dispersive regime (detuning >> coupling), the readout
//! resonator acquires a qubit-state-dependent frequency shift (dispersive
//! shift chi = g^2 / Delta). Measuring the transmitted/reflected microwave
//! signal produces IQ-plane data whose location encodes the qubit state.
//!
//! # Physical Model
//!
//! The dispersive Hamiltonian in the rotating frame of the resonator:
//!
//! ```text
//! H_disp = chi * a†a * sigma_z / 2
//! ```
//!
//! The resonator response to a readout drive at frequency omega_d:
//!
//! ```text
//! alpha_k = 2 * g * sqrt(n_bar) / (kappa + 2i*(omega_r - omega_d ± chi))
//! ```
//!
//! where k in {0, 1} labels the qubit state, kappa is the resonator linewidth,
//! and the sign of chi depends on the qubit state.
//!
//! IQ separation determines readout fidelity; Gaussian noise from photon
//! shot noise and thermal fluctuations limits discrimination.
//!
//! # Example
//!
//! ```rust,ignore
//! use nqpu_metal::dispersive_readout::*;
//! use num_complex::Complex64;
//!
//! let config = ReadoutConfig {
//!     resonator_freq_ghz: 7.0,
//!     coupling_ghz: 0.1,
//!     kappa_mhz: 2.0,
//!     readout_duration_ns: 1000.0,
//!     thermal_noise_amplitude: 0.05,
//! };
//! let sim = ReadoutSimulator::new(config, 5.0);
//! let chi = sim.dispersive_shift_mhz();
//! assert!(chi > 0.0);
//!
//! // Readout of |0> state
//! let state_0 = vec![Complex64::new(1.0, 0.0), Complex64::new(0.0, 0.0)];
//! let result = sim.readout(&state_0, 42);
//! assert_eq!(result.classified_state, 0);
//! ```

use num_complex::Complex64;
use std::f64::consts::PI;

// ============================================================
// COMPLEX NUMBER HELPERS (local to this module)
// ============================================================

const ZERO: Complex64 = Complex64 { re: 0.0, im: 0.0 };
const ONE: Complex64 = Complex64 { re: 1.0, im: 0.0 };

#[inline]
fn c(re: f64, im: f64) -> Complex64 {
    Complex64::new(re, im)
}

#[inline]
fn c_re(re: f64) -> Complex64 {
    Complex64::new(re, 0.0)
}

// ============================================================
// READOUT CONFIGURATION
// ============================================================

/// Configuration parameters for the dispersive readout resonator.
///
/// These map to experimentally calibrated device parameters.
/// Typical IBM transmon values: resonator ~ 6.5-7.5 GHz, coupling ~ 50-150 MHz,
/// kappa ~ 1-5 MHz, readout duration ~ 500-2000 ns.
#[derive(Clone, Debug)]
pub struct ReadoutConfig {
    /// Readout resonator frequency in GHz.
    pub resonator_freq_ghz: f64,
    /// Qubit-resonator coupling strength g in GHz.
    pub coupling_ghz: f64,
    /// Resonator linewidth (decay rate) kappa in MHz.
    pub kappa_mhz: f64,
    /// Total readout integration time in nanoseconds.
    pub readout_duration_ns: f64,
    /// Amplitude of additive Gaussian noise per quadrature.
    /// Models thermal + amplifier noise. Typical range: 0.01 - 0.2.
    pub thermal_noise_amplitude: f64,
}

impl Default for ReadoutConfig {
    fn default() -> Self {
        Self {
            resonator_freq_ghz: 7.0,
            coupling_ghz: 0.1,
            kappa_mhz: 2.0,
            readout_duration_ns: 1000.0,
            thermal_noise_amplitude: 0.05,
        }
    }
}

// ============================================================
// READOUT RESULT
// ============================================================

/// Result of a single-shot dispersive readout measurement.
#[derive(Clone, Debug)]
pub struct ReadoutResult {
    /// Measured IQ point (I = real, Q = imaginary) in arbitrary units.
    pub iq_point: Complex64,
    /// Classified qubit state (0 or 1) based on IQ discrimination.
    pub classified_state: u8,
    /// Born-rule probability of the classified state before measurement.
    pub probability: f64,
}

// ============================================================
// DISCRIMINATION REPORT
// ============================================================

/// Statistical report characterizing the readout discriminator.
///
/// Generated by injecting known |0> and |1> states many times and
/// computing the IQ cloud statistics.
#[derive(Clone, Debug)]
pub struct DiscriminationReport {
    /// IQ centroid for the |0> state cloud.
    pub center_0: Complex64,
    /// IQ centroid for the |1> state cloud.
    pub center_1: Complex64,
    /// Euclidean distance between centroids in IQ plane.
    pub separation: f64,
    /// Signal-to-noise ratio: separation / average cloud standard deviation.
    pub snr: f64,
    /// Assignment fidelity: fraction of shots correctly classified.
    /// F_assign = 1 - (P(1|0) + P(0|1)) / 2
    pub assignment_fidelity: f64,
}

// ============================================================
// SEEDED PRNG (xoshiro256** for reproducibility without external deps)
// ============================================================

/// Minimal xoshiro256** PRNG for deterministic, seeded noise generation.
/// We avoid pulling in `rand` thread-level state so that tests are
/// reproducible with an explicit seed.
struct Rng {
    s: [u64; 4],
}

impl Rng {
    fn new(seed: u64) -> Self {
        // SplitMix64 to expand a single seed into 256 bits of state.
        let mut z = seed;
        let mut s = [0u64; 4];
        for slot in &mut s {
            z = z.wrapping_add(0x9e3779b97f4a7c15);
            let mut v = z;
            v = (v ^ (v >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
            v = (v ^ (v >> 27)).wrapping_mul(0x94d049bb133111eb);
            *slot = v ^ (v >> 31);
        }
        Self { s }
    }

    fn next_u64(&mut self) -> u64 {
        let result = (self.s[1].wrapping_mul(5)).rotate_left(7).wrapping_mul(9);
        let t = self.s[1] << 17;
        self.s[2] ^= self.s[0];
        self.s[3] ^= self.s[1];
        self.s[1] ^= self.s[2];
        self.s[0] ^= self.s[3];
        self.s[2] ^= t;
        self.s[3] = self.s[3].rotate_left(45);
        result
    }

    /// Uniform f64 in [0, 1).
    fn next_f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// Standard normal via Box-Muller transform.
    fn next_gaussian(&mut self) -> f64 {
        loop {
            let u1 = self.next_f64();
            let u2 = self.next_f64();
            if u1 > 1e-30 {
                return (-2.0 * u1.ln()).sqrt() * (2.0 * PI * u2).cos();
            }
        }
    }
}

// ============================================================
// READOUT SIMULATOR
// ============================================================

/// Dispersive readout simulator for a single transmon qubit coupled
/// to a readout resonator.
///
/// Computes IQ centroids from the steady-state resonator response in
/// the dispersive limit, adds Gaussian noise scaled by the readout
/// duration and resonator linewidth, and classifies the result.
#[derive(Clone, Debug)]
pub struct ReadoutSimulator {
    config: ReadoutConfig,
    /// Qubit transition frequency in GHz.
    qubit_freq_ghz: f64,
    /// Dispersive shift chi in GHz (computed from g^2 / Delta).
    chi_ghz: f64,
    /// IQ centroid for qubit in |0>.
    center_0: Complex64,
    /// IQ centroid for qubit in |1>.
    center_1: Complex64,
    /// Noise standard deviation per quadrature.
    noise_sigma: f64,
}

impl ReadoutSimulator {
    /// Create a new readout simulator.
    ///
    /// # Arguments
    /// * `config` - Resonator and readout parameters.
    /// * `qubit_freq_ghz` - Qubit transition frequency in GHz.
    ///
    /// # Physics
    ///
    /// The dispersive shift is chi = g^2 / |Delta| where Delta = qubit_freq - resonator_freq.
    /// IQ centroids come from the resonator steady-state response driven at the bare
    /// resonator frequency:
    ///
    /// ```text
    /// alpha_k = A / (kappa/2 + i * delta_k)
    /// ```
    ///
    /// where delta_0 = -chi, delta_1 = +chi (frequency shifts for |0> and |1>),
    /// and A is a drive-strength factor proportional to g * sqrt(n_photons).
    pub fn new(config: ReadoutConfig, qubit_freq_ghz: f64) -> Self {
        let delta_ghz = (qubit_freq_ghz - config.resonator_freq_ghz).abs();
        // Dispersive shift: chi = g^2 / Delta
        let chi_ghz = if delta_ghz > 1e-12 {
            config.coupling_ghz * config.coupling_ghz / delta_ghz
        } else {
            0.0
        };

        // Convert kappa from MHz to GHz for consistent units.
        let kappa_ghz = config.kappa_mhz * 1e-3;

        // Drive amplitude factor. We assume the readout drive is at the bare
        // resonator frequency with mean photon number n_bar ~ 1. The overall
        // scale A = 2 * g * sqrt(n_bar) is in GHz; we keep it in GHz and
        // normalise to "arbitrary IQ units" later.
        let n_bar: f64 = 1.0;
        let drive_a = 2.0 * config.coupling_ghz * n_bar.sqrt();

        // Steady-state intracavity field for qubit in |0> and |1>.
        // alpha_k = A / (kappa/2 + i * delta_k)
        // Drive at bare resonator freq => detuning from dressed freq is ∓ chi.
        let half_kappa = kappa_ghz / 2.0;
        let denom_0 = c(half_kappa, -chi_ghz); // delta_0 = -chi
        let denom_1 = c(half_kappa, chi_ghz);  // delta_1 = +chi

        let center_0 = c_re(drive_a) / denom_0;
        let center_1 = c_re(drive_a) / denom_1;

        // Noise sigma: shot noise + thermal noise.
        // Shot noise scales as sqrt(kappa * T_readout) in natural units;
        // we add the user-specified thermal noise amplitude.
        let kappa_per_ns = kappa_ghz * 2.0 * PI; // angular rate in rad/ns
        let shot_noise = (kappa_per_ns * config.readout_duration_ns).sqrt();
        // Normalise shot noise to the same IQ scale as the centroids.
        // The centroid magnitude is O(drive_a / kappa); shot noise per quadrature
        // is O(1/sqrt(n_photons * kappa * T)). We scale it relative to the
        // centroid separation so the SNR formula stays clean.
        let separation = (center_1 - center_0).norm();
        let noise_sigma = if separation > 1e-30 {
            // Physical noise: fraction of separation.
            // sqrt(1/(kappa*T)) gives photon-resolved noise relative to signal;
            // we add thermal_noise_amplitude as a baseline.
            let photon_noise = 1.0 / shot_noise.max(1e-30);
            (photon_noise + config.thermal_noise_amplitude) * separation
        } else {
            config.thermal_noise_amplitude
        };

        Self {
            config,
            qubit_freq_ghz,
            chi_ghz,
            center_0,
            center_1,
            noise_sigma,
        }
    }

    /// Return the dispersive shift chi in MHz.
    ///
    /// chi = g^2 / |Delta| converted to MHz.
    pub fn dispersive_shift_mhz(&self) -> f64 {
        self.chi_ghz * 1e3 // GHz -> MHz
    }

    /// Perform a single-shot dispersive readout on the given qubit state.
    ///
    /// The state vector must have length >= 2. Only the first two
    /// amplitudes (computational subspace |0>, |1>) are used.
    ///
    /// # Arguments
    /// * `state` - Qubit statevector (at least 2 amplitudes).
    /// * `seed` - RNG seed for reproducible noise.
    ///
    /// # Returns
    /// A `ReadoutResult` with the noisy IQ point, classified state, and
    /// the Born-rule probability of the classified outcome.
    pub fn readout(&self, state: &[Complex64], seed: u64) -> ReadoutResult {
        assert!(state.len() >= 2, "State must have at least 2 amplitudes");

        let p0 = state[0].norm_sqr();
        let p1 = state[1].norm_sqr();

        let mut rng = Rng::new(seed);

        // Decide which state the qubit is actually in (projective measurement).
        let r = rng.next_f64();
        let (true_state, center, prob) = if r < p0 / (p0 + p1) {
            (0u8, self.center_0, p0)
        } else {
            (1u8, self.center_1, p1)
        };

        // Add Gaussian noise to the IQ point.
        let noise_i = self.noise_sigma * rng.next_gaussian();
        let noise_q = self.noise_sigma * rng.next_gaussian();
        let iq_point = center + c(noise_i, noise_q);

        // Classify: which centroid is the noisy IQ point closer to?
        let dist_0 = (iq_point - self.center_0).norm();
        let dist_1 = (iq_point - self.center_1).norm();
        let classified_state = if dist_0 <= dist_1 { 0 } else { 1 };

        ReadoutResult {
            iq_point,
            classified_state,
            probability: prob,
        }
    }

    /// Perform many readout shots and collect statistics.
    ///
    /// Each shot uses a different RNG seed derived from `seed` to ensure
    /// independence while remaining deterministic.
    ///
    /// # Arguments
    /// * `state` - Qubit statevector.
    /// * `num_shots` - Number of measurement repetitions.
    /// * `seed` - Base RNG seed.
    pub fn batch_readout(
        &self,
        state: &[Complex64],
        num_shots: usize,
        seed: u64,
    ) -> Vec<ReadoutResult> {
        (0..num_shots)
            .map(|i| {
                // Derive per-shot seed via splitmix-style mixing to avoid
                // correlated streams.
                let shot_seed = seed
                    .wrapping_add(i as u64)
                    .wrapping_mul(0x9e3779b97f4a7c15)
                    ^ (i as u64).wrapping_mul(0x517cc1b727220a95);
                self.readout(state, shot_seed)
            })
            .collect()
    }

    /// Generate a discrimination report by probing the readout with
    /// ideal |0> and |1> states.
    ///
    /// This mirrors the calibration procedure performed on real hardware:
    /// prepare |0> N times, prepare |1> N times, build the IQ clouds,
    /// and compute assignment fidelity.
    ///
    /// # Arguments
    /// * `num_shots` - Shots per state (total shots = 2 * num_shots).
    /// * `seed` - Base RNG seed.
    pub fn discrimination_analysis(
        &self,
        num_shots: usize,
        seed: u64,
    ) -> DiscriminationReport {
        let state_0 = [ONE, ZERO];
        let state_1 = [ZERO, ONE];

        let results_0 = self.batch_readout(&state_0, num_shots, seed);
        let results_1 = self.batch_readout(&state_1, num_shots, seed.wrapping_add(0xDEADBEEF));

        // Compute empirical centroids from the IQ clouds.
        let mean_0 = iq_mean(&results_0);
        let mean_1 = iq_mean(&results_1);

        let separation = (mean_1 - mean_0).norm();

        // Standard deviations of each cloud (averaged across I and Q).
        let std_0 = iq_std(&results_0, mean_0);
        let std_1 = iq_std(&results_1, mean_1);
        let avg_std = (std_0 + std_1) / 2.0;

        let snr = if avg_std > 1e-30 {
            separation / avg_std
        } else {
            f64::INFINITY
        };

        // Assignment fidelity: F = 1 - (P(1|0) + P(0|1)) / 2
        let misclass_0 = results_0
            .iter()
            .filter(|r| r.classified_state != 0)
            .count() as f64
            / num_shots as f64;
        let misclass_1 = results_1
            .iter()
            .filter(|r| r.classified_state != 1)
            .count() as f64
            / num_shots as f64;
        let assignment_fidelity = 1.0 - (misclass_0 + misclass_1) / 2.0;

        DiscriminationReport {
            center_0: mean_0,
            center_1: mean_1,
            separation,
            snr,
            assignment_fidelity,
        }
    }

    /// Access the precomputed IQ centroid for |0>.
    pub fn iq_center_0(&self) -> Complex64 {
        self.center_0
    }

    /// Access the precomputed IQ centroid for |1>.
    pub fn iq_center_1(&self) -> Complex64 {
        self.center_1
    }

    /// Access the noise standard deviation per quadrature.
    pub fn noise_sigma(&self) -> f64 {
        self.noise_sigma
    }
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/// Mean IQ point from a batch of readout results.
fn iq_mean(results: &[ReadoutResult]) -> Complex64 {
    if results.is_empty() {
        return ZERO;
    }
    let sum: Complex64 = results.iter().map(|r| r.iq_point).sum();
    sum / c_re(results.len() as f64)
}

/// Standard deviation of IQ cloud (RMS distance from centroid).
fn iq_std(results: &[ReadoutResult], mean: Complex64) -> f64 {
    if results.len() < 2 {
        return 0.0;
    }
    let var: f64 = results
        .iter()
        .map(|r| (r.iq_point - mean).norm_sqr())
        .sum::<f64>()
        / (results.len() - 1) as f64;
    var.sqrt()
}

// ============================================================
// TESTS
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;

    const TOL: f64 = 1e-3;

    fn default_config() -> ReadoutConfig {
        ReadoutConfig {
            resonator_freq_ghz: 7.0,
            coupling_ghz: 0.1,
            kappa_mhz: 2.0,
            readout_duration_ns: 1000.0,
            thermal_noise_amplitude: 0.05,
        }
    }

    // ----------------------------------------------------------
    // 1. Dispersive shift matches g^2 / Delta
    // ----------------------------------------------------------
    #[test]
    fn test_dispersive_shift_matches_g_squared_over_delta() {
        let config = default_config();
        let qubit_freq = 5.0; // GHz
        let sim = ReadoutSimulator::new(config.clone(), qubit_freq);

        let delta = (qubit_freq - config.resonator_freq_ghz).abs(); // 2.0 GHz
        let expected_chi_ghz = config.coupling_ghz * config.coupling_ghz / delta; // 0.01 / 2.0 = 0.005 GHz
        let expected_chi_mhz = expected_chi_ghz * 1e3; // 5.0 MHz

        let actual = sim.dispersive_shift_mhz();
        assert!(
            (actual - expected_chi_mhz).abs() < TOL,
            "Dispersive shift: expected {:.4} MHz, got {:.4} MHz",
            expected_chi_mhz,
            actual
        );
    }

    // ----------------------------------------------------------
    // 2. Dispersive shift scales with coupling squared
    // ----------------------------------------------------------
    #[test]
    fn test_dispersive_shift_scales_with_coupling() {
        let qubit_freq = 5.0;
        let mut config1 = default_config();
        config1.coupling_ghz = 0.05;
        let sim1 = ReadoutSimulator::new(config1, qubit_freq);

        let mut config2 = default_config();
        config2.coupling_ghz = 0.10;
        let sim2 = ReadoutSimulator::new(config2, qubit_freq);

        // Doubling g should quadruple chi.
        let ratio = sim2.dispersive_shift_mhz() / sim1.dispersive_shift_mhz();
        assert!(
            (ratio - 4.0).abs() < 0.01,
            "chi should scale as g^2: expected ratio 4.0, got {:.4}",
            ratio
        );
    }

    // ----------------------------------------------------------
    // 3. Readout classifies |0> correctly
    // ----------------------------------------------------------
    #[test]
    fn test_readout_classifies_ground_state() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);

        let state_0 = [ONE, ZERO];
        let result = sim.readout(&state_0, 42);

        assert_eq!(
            result.classified_state, 0,
            "Ground state should be classified as 0"
        );
        assert!(
            (result.probability - 1.0).abs() < TOL,
            "Probability should be ~1.0 for pure |0>"
        );
    }

    // ----------------------------------------------------------
    // 4. Readout classifies |1> correctly
    // ----------------------------------------------------------
    #[test]
    fn test_readout_classifies_excited_state() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);

        let state_1 = [ZERO, ONE];
        let result = sim.readout(&state_1, 42);

        assert_eq!(
            result.classified_state, 1,
            "Excited state should be classified as 1"
        );
        assert!(
            (result.probability - 1.0).abs() < TOL,
            "Probability should be ~1.0 for pure |1>"
        );
    }

    // ----------------------------------------------------------
    // 5. IQ centroids are distinct (separation > 0)
    // ----------------------------------------------------------
    #[test]
    fn test_iq_centroids_separated() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);

        let sep = (sim.iq_center_1() - sim.iq_center_0()).norm();
        assert!(
            sep > 1e-6,
            "IQ centroids should be well-separated, got separation = {:.6e}",
            sep
        );
    }

    // ----------------------------------------------------------
    // 6. Batch readout statistics match expected distribution
    // ----------------------------------------------------------
    #[test]
    fn test_batch_readout_statistics() {
        let config = ReadoutConfig {
            thermal_noise_amplitude: 0.01, // Low noise for clean statistics
            ..default_config()
        };
        let sim = ReadoutSimulator::new(config, 5.0);

        // Superposition: |+> = (|0> + |1>) / sqrt(2)
        let s = 1.0 / 2.0f64.sqrt();
        let state_plus = [c_re(s), c_re(s)];

        let results = sim.batch_readout(&state_plus, 10_000, 12345);
        let count_0 = results.iter().filter(|r| r.classified_state == 0).count();
        let count_1 = results.len() - count_0;

        let frac_0 = count_0 as f64 / results.len() as f64;
        let frac_1 = count_1 as f64 / results.len() as f64;

        // Should be close to 50/50 (within ~3% for 10k shots).
        assert!(
            (frac_0 - 0.5).abs() < 0.05,
            "Expected ~50% |0>, got {:.1}%",
            frac_0 * 100.0
        );
        assert!(
            (frac_1 - 0.5).abs() < 0.05,
            "Expected ~50% |1>, got {:.1}%",
            frac_1 * 100.0
        );
    }

    // ----------------------------------------------------------
    // 7. Discrimination analysis produces SNR > 1
    // ----------------------------------------------------------
    #[test]
    fn test_discrimination_snr_above_one() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);

        let report = sim.discrimination_analysis(5_000, 99);

        assert!(
            report.snr > 1.0,
            "SNR should be > 1 for reasonable parameters, got {:.3}",
            report.snr
        );
        assert!(
            report.separation > 1e-6,
            "Separation should be positive, got {:.6e}",
            report.separation
        );
    }

    // ----------------------------------------------------------
    // 8. Assignment fidelity exceeds 0.9 with good parameters
    // ----------------------------------------------------------
    #[test]
    fn test_assignment_fidelity_reasonable() {
        let config = ReadoutConfig {
            thermal_noise_amplitude: 0.02, // Low noise
            readout_duration_ns: 2000.0,   // Long integration
            ..default_config()
        };
        let sim = ReadoutSimulator::new(config, 5.0);

        let report = sim.discrimination_analysis(5_000, 77);

        assert!(
            report.assignment_fidelity > 0.9,
            "Assignment fidelity should exceed 0.9, got {:.4}",
            report.assignment_fidelity
        );
    }

    // ----------------------------------------------------------
    // 9. Noise sigma is positive
    // ----------------------------------------------------------
    #[test]
    fn test_noise_sigma_positive() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);
        assert!(
            sim.noise_sigma() > 0.0,
            "Noise sigma should be positive, got {}",
            sim.noise_sigma()
        );
    }

    // ----------------------------------------------------------
    // 10. Deterministic: same seed produces same result
    // ----------------------------------------------------------
    #[test]
    fn test_readout_deterministic_with_same_seed() {
        let config = default_config();
        let sim = ReadoutSimulator::new(config, 5.0);

        let s = 1.0 / 2.0f64.sqrt();
        let state = [c_re(s), c_re(s)];

        let r1 = sim.readout(&state, 42);
        let r2 = sim.readout(&state, 42);

        assert_eq!(
            r1.iq_point, r2.iq_point,
            "Same seed should produce identical IQ points"
        );
        assert_eq!(
            r1.classified_state, r2.classified_state,
            "Same seed should produce identical classification"
        );
    }

    // ----------------------------------------------------------
    // 11. Zero coupling gives zero dispersive shift
    // ----------------------------------------------------------
    #[test]
    fn test_zero_coupling_zero_shift() {
        let config = ReadoutConfig {
            coupling_ghz: 0.0,
            ..default_config()
        };
        let sim = ReadoutSimulator::new(config, 5.0);
        assert!(
            sim.dispersive_shift_mhz().abs() < 1e-12,
            "Zero coupling should give zero dispersive shift"
        );
    }
}
